on: 
  push:
    branches:
      - "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 15
      - name: build of the code
        run: |
          npm install
          npm run lint 
          npm run prettier -- --write
          CI=true npm run test
          npm run build 
        working-directory: codebase/rdicidr-0.1.0/
